apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging-frontend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/KeremAR/proxmox-k3s'
    path: helm-charts/frontend
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
      parameters:
        # Image tag (updated by Jenkins CI/CD)
        - name: image.tag
          value: 'a53131e'
        # Staging-specific overrides
        - name: deployment.replicas
          value: '1'
        - name: resources.requests.cpu
          value: '100m'
        - name: resources.requests.memory
          value: '128Mi'
        - name: resources.limits.cpu
          value: '250m'
        - name: resources.limits.memory
          value: '256Mi'
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
