apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging-frontend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/KeremAR/proxmox-k3s'
    path: helm-charts/frontend
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
        - values-staging.yaml
      parameters:
        # Image tag (updated by Jenkins CI/CD)
        - name: image.tag
          value: 'd40d855'
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
