apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: production-todo-service
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/KeremAR/proxmox-k3s'
    path: helm-charts/todo-service
    targetRevision: main  # Can be a tag for production
    helm:
      valueFiles:
        - values.yaml
        - values-prod.yaml
      parameters:
        # Image tag (managed by production deployment process)
        - name: image.tag
          value: 'latest'
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
