apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: production-todo-service
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/KeremAR/proxmox-k3s'
    path: helm-charts/todo-service
    targetRevision: main  # Can be a tag for production
    helm:
      valueFiles:
        - values.yaml
      parameters:
        # Image tag (updated by Jenkins CI/CD)
        - name: image.tag
          value: 'latest'
        # Production-specific overrides
        - name: deployment.replicas
          value: '3'
        - name: resources.requests.cpu
          value: '200m'
        - name: resources.requests.memory
          value: '256Mi'
        - name: resources.limits.cpu
          value: '500m'
        - name: resources.limits.memory
          value: '512Mi'
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
